services:
  db: 
    image: postgres:17
    environment:
      POSTGRES_USER: bloggregator
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bloggregator
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: