feeds: 
    - https://simonwillison.net/atom/entries/
    - https://feeds.feedburner.com/ThePragmaticEngineer
    - https://feeds.feedburner.com/TheDailyWtf
    - https://jvns.ca/atom.xml
    - https://danluu.com/atom.xml
    - https://akitaonrails.com/index.xml

polling:
    frequency: 2
    start_time: "10:00"